services:
  - type: web
    name: ai-crm-assistant
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npx next start -p $PORT
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 20
      # Set these in Render Dashboard → Environment (do not commit secrets)
      # - key: MONGODB_URI
      #   sync: false
      # - key: OPENAI_API_KEY
      #   sync: false
      # - key: NEXT_PUBLIC_APP_URL
      #   value: https://<your-service>.onrender.com
    healthCheckPath: /
